VACMS-18108: Removing trait due to phpunit errors being thrown depending on how the test was run. Using a filter would cause the tests to pass when targetting specific test methods, but when testing a specific group, the tests would fail with 'ArgumentCountError: Too few arguments to function tests\phpunit\Migration\VaFacilityNcaMigrationTest::testMockedJsonDataFetchMigration()' or similar.