Fix "self signed certificate in chain" error on deploys. (#1162)
* Add .env.global & PUPPETEER_SKIP_CHROMIUM_DOWNLOAD='TRUE'.

The error we are seeing with network flickers is below and this is the
most common one, it won't solve everything but will help stop the
bleeding.

We don't use the Chromium package in any of our tests. The FE team may
use it in theirs but we don't in CMS.

ERROR: Failed to download Chromium r594312! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
at TLSSocket.emit (events.js:189:13)
at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
Script cd web && yarn install handling the va:web:install event returned with error code 1
Script @va:web:install was called via post-install-cmd

* Add NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt.

This gets rid of the "self signed certificate in chain" error.

* Always use source to install Drupal, zipball is blocked by TIC.

This solves this error below with a 3 try failure w/fallback to source, so just jump straight to source download.

> Failed to execute unzip -qq  'docroot/core/7d8cefd31e46b5644522f9d27e1596ff'
> Invalid zip file, retrying.

Which is actually caused by a GITHUB-DOWNLOADING AppID block by the VA
TIC (SNOW TICKET).

* Add temp debug yarn --verbose.

* export NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=TRUE; cd web && yarn install

Trust the VA CAs so downloads don't throw "self signed certificate in chain" errors. e.g. Chromium.

Puppeteer's Chromium download takes about 30 seconds on the network and we don't use Chromium (or Puppeteer) for CMS testing right now so skip.
e.g. https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/686378/chrome-linux.zip

This wasn't possible using .env files as they weren't loading into the
`node` subprocess but a direct `export` is working.

Co-authored-by: Jon Pugh <jon@thinkdrop.net>
Co-authored-by: Steve Wirt <swirtSJW@users.noreply.github.com>