VACMS-18108: Updates references to v0 to v1 (#18149)
* VACMS-18108: Updates references to v0 to v1

* VACMS-18108: Updates settings

* VACMS-18108: Restores file to main.

* VACMS-18108: Update config after header change

* VACMS-18108: Updates endpoints

* VACMS-18108: Update the call

* VACMS-18108: Updates NCA migration yml

* VACMS-18108: Updates the NCA migration and calls to URLs for settings.

* VACMS-18108: Updates migration test data files

* VACMS-18108: Adds settings to call all of the facilities

* VACMS-18108: Updates the migration files for all types

* VACMS-18108: Updates settings.php to makes local settings.

* VACMS-18108: Updates facility test fixtures to contain an outter array.
- Updates the testVaLocalHealthCareFacilityMigration test to include setting url override to prevent guzzle client error.

* VACMS-18108: Changes the phone selector to match exptected data structure.

* VACMS-18108: Adds migration test trait and implements it in facility migration tests for DRY purposes.
- Updates .json data to match expected values.

* VACMS-18108: Removing trait due to phpunit errors being thrown depending on how the test was run. Using a filter would cause the tests to pass when targetting specific test methods, but when testing a specific group, the tests would fail with 'ArgumentCountError: Too few arguments to function tests\phpunit\Migration\VaFacilityNcaMigrationTest::testMockedJsonDataFetchMigration()' or similar.

* VACMS-18108: Aligns the source uls with other migrations.

---------

Co-authored-by: Daniel Sasser <daniel.sasser@agile6.com>