Add .env.global & PUPPETEER_SKIP_CHROMIUM_DOWNLOAD='TRUE'.
The error we are seeing with network flickers is below and this is the
most common one, it won't solve everything but will help stop the
bleeding.

We don't use the Chromium package in any of our tests. The FE team may
use it in theirs but we don't in CMS.

ERROR: Failed to download Chromium r594312! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
at TLSSocket.emit (events.js:189:13)
at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
Script cd web && yarn install handling the va:web:install event returned with error code 1
Script @va:web:install was called via post-install-cmd